MangoDrink/urls.py
from django.urls import path
from MangoDrink import views
from Mango import urls

app_name = 'MangoDrink'
urlpatterns = [
    path('', views.index, name='index'),
    path('other', views.other, name='other'),
    path('information', views.information, name='information'),
]

urls.py
from django.contrib import admin
from django.urls import path, include
from MangoDrink import views
from MangoDrink import urls

urlpatterns = [
    path('', views.index, name='index'),
    path('other', views.other, name='other'),
    path('information', views.information, name='information'),
    path('other', include('MangoDrink.urls')),
    path('information', include('MangoDrink.urls')),
    path('admin/', admin.site.urls),
]

MangoDrink/models.py
from django.db import models

# Create your models here.

MangoDrink/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'MangoDrink/index.html')

def other(request):
    return render(request, 'MangoDrink/other.html')

def information(request):
    return render(request, 'MangoDrink/information.html')

templates/MangoDrink/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Index</title>
  </head>
  <body>
    <h1>Index</h1>
  </body>
</html>

templates/MangoDrink/information.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Information</h1>
    <a href="{% url 'MangoDrink:other' %}">The Other Page</a>
  </body>
</html>

templates/MangoDrink/other.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Other</h1>
  </body>
</html>